name: photo_revive
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 2.0.0+1
  retrofit: 3.3.1
  analyzer: 5.4.0
  dio: 4.0.6
  json_serializable: 6.6.1
  dartz: 0.10.1

  cupertino_icons: ^1.0.2
  internet_connection_checker: 1.0.0+1
  shared_preferences: 2.0.17
  freezed: 2.3.2
  get_it: 7.2.0
  lottie: 2.2.0
  image_picker: 0.8.6+1
  rxdart: 0.27.7
  carousel_slider: 4.2.1
  easy_localization: 3.0.1
  flutter_phoenix: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: 4.2.0
  build_runner: 2.3.3

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

scripts:
  gf: flutter pub run build_runner build --delete-conflicting-outputs
